//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstraintsForPlacementTable
    {
        public long InputCodeForPlacement { get; set; }
        public Nullable<long> InlayCode { get; set; }
        public Nullable<long> AuthorCodeForInlay { get; set; }
        public Nullable<long> ForcedOptionCode { get; set; }
        public Nullable<long> ForWhomTheInlay { get; set; }
    
        public virtual InlayOptionsTable InlayOptionsTable { get; set; }
        public virtual InlayTable InlayTable { get; set; }
        public virtual UsersTable UsersTable { get; set; }
        public virtual UsersTable UsersTable1 { get; set; }
    }
}
