//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstraintsTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConstraintsTable()
        {
            this.InlayOptionsTable = new HashSet<InlayOptionsTable>();
        }
    
        public long ConstraintCode { get; set; }
        public string NameConstraint { get; set; }
        public Nullable<long> UserType { get; set; }
    
        public virtual UserTypesTable UserTypesTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InlayOptionsTable> InlayOptionsTable { get; set; }
    }
}
