//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClassificationEntities1 : DbContext
    {
        public ClassificationEntities1()
            : base("name=ClassificationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ConstraintsForPlacementTable> ConstraintsForPlacementTable { get; set; }
        public virtual DbSet<ConstraintsTable> ConstraintsTable { get; set; }
        public virtual DbSet<InlayOptionsTable> InlayOptionsTable { get; set; }
        public virtual DbSet<InlayTable> InlayTable { get; set; }
        public virtual DbSet<InstitutionsTables> InstitutionsTables { get; set; }
        public virtual DbSet<UsersTable> UsersTable { get; set; }
        public virtual DbSet<UserTypesTable> UserTypesTable { get; set; }


        public DbSet<T> GetDbSet<T>() where T : class
        {
            return this.Set<T>();
        }

        }
    }
