//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InlaySlot
    {
        public long SlotCode { get; set; }
        public Nullable<long> InlayCode { get; set; }
        public Nullable<long> StudentCode { get; set; }
        public Nullable<int> NumOfClass { get; set; }
    
        public virtual Inlays Inlays { get; set; }
    }
}
