//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentPlacementEntities : DbContext
    {
        public StudentPlacementEntities()
            : base("name=StudentPlacementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AreasInCity> AreasInCity { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<EducationalInstitutions> EducationalInstitutions { get; set; }
        public virtual DbSet<Inlays> Inlays { get; set; }
        public virtual DbSet<InlaySlot> InlaySlot { get; set; }
        public virtual DbSet<School> School { get; set; }
        public virtual DbSet<Students> Students { get; set; }


        public DbSet<T> GetDbSet<T>() where T : class
        {
            return this.Set<T>();
        }
    }

  

}
