//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        public long StudentCode { get; set; }
        public string StudentName { get; set; }
        public Nullable<long> AreaCityCode { get; set; }
        public Nullable<double> GradePointAverage { get; set; }
        public Nullable<int> SocialInvolvement { get; set; }
        public Nullable<long> PreviousSchoolCode { get; set; }
        public Nullable<long> InstitutionCode { get; set; }
    
        public virtual AreasInCity AreasInCity { get; set; }
        public virtual EducationalInstitutions EducationalInstitutions { get; set; }
        public virtual School School { get; set; }
    }
}
